version: '3'

services:
  api:
    restart: on-failure
    build: .
    env_file: .env
    links:
      - postgres
#      - minio

  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postggres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "/opt/docker-data/ossmi/pg-data:/var/lib/postgresql/data"
    ports:
      - "5032:5432"
    hostname: postgres

#networks:
